### ISSUE TITLE
Troubles with  LibreOffice

### ISSUE THREAD

**Issue by pedroreartes** [shuchkin/simplexlsx#1]
Hi,  Your library is excelent!. Congratulations to you. Works grate.

I found this issue:
When I try to load an xlsx file saved with libreoffice, got an error,
so, I edit the worksheet function

```
 // sheets numeration: 1,2,3....
    public function rows( $worksheet_id = 1 ) {
```

//AND ADD THIS LINES, BEACOUSE; $this->sheets[$index] **$index starts on 2**
and **$this->sheets[1] was not defined**.

```
  //fix libreoffice error
        if(!isset($this->sheets[1]) && isset($this->sheets[2])){
            $this->sheets[1] = $this->sheets[2];
        }
```

The libreoffice I'm using:
Version: 4.3.3.2
Build ID: 430m0(Build:2)

and save file as Microsoft Excel 2007/2010/2013 (xlsx)

Excelente trabajo!
Saludos!

**Comment by shuchkin** [comment]
Hello, Pedro.

thx :)

give me your xlsx


> Hi,  Your library is excelent!. Congratulations to you. Works grate.
>  I found this issue:
> When I try to load an xlsx file saved with libreoffice, got an error,
> so, I edit the worksheet function
>  // sheets numeration: 1,2,3....
> public function rows( $worksheet_id = 1 ) {
>  //AND ADD THIS LINES, BEACOUSE; $this->sheets[$index] $index start on 2
and $this->>sheets[1] was not defined.
>  //fix libreoffice error
if(!isset($this->>sheets[1]) && isset($this->sheets[2])){
$this->>sheets[1] = $this->sheets[2];
> }
>  The libreoffice I'm using:
> Version: 4.3.3.2
> Build ID: 430m0(Build:2)
>  and save file as Microsoft Excel 2007/2010/2013 (xlsx)
>  Excelente trabajo!
> Saludos!
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
>   
>     
> {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/shuchkin/simplexlsx","title":"shuchkin/simplexlsx","subtitle":"GitHub
> repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open
> in
> GitHub","url":"https://github.com/shuchkin/simplexlsx"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Troubles
> with  LibreOffice (#1)"}],"action":{"name":"View
> Issue","url":"https://github.com/shuchkin/simplexlsx/issues/1"}}} 



-- 
Thank You
Sergey
http://www.sibvision.ru/
http://www.smspilot.ru/
https://twitter.com/shuchkin
https://www.facebook.com/shuchkin

**Comment by Kukulkano** [comment]
I can confirm the issue. Most recent simplexlsx version is still having troubles to open some xlsx file created by LibreOffice (LibreOffice V5.3.1.2 on Kubuntu 16.04).
[upload_template.xlsx](https://github.com/shuchkin/simplexlsx/files/885213/upload_template.xlsx)

**Comment by mandito67** [comment]
Hello! Excelente work!!

In my case the sheet id was number 3, I found that when print_r the sheet names, the only one was [3]=>Hoja1.
So, I add after the solution Pedro (but in another function) post a second check for id 3. I worked for me to solve quickly.

public function worksheet( $worksheet_id ) {

		if(!isset($this->sheets[1]) && isset($this->sheets[2])){
            $this->sheets[1] = $this->sheets[2];
            $worksheet_id = 2;
        }else if(!isset($this->sheets[2]) && isset($this->sheets[3])){
        	$this->sheets[1] = $this->sheets[3];
            $worksheet_id = 3;
        }

		if ( isset( $this->sheets[ $worksheet_id ] ) ) {
			$ws = $this->sheets[ $worksheet_id ];
			
			if (isset($ws->hyperlinks)) {
				$this->hyperlinks = array();
				foreach( $ws->hyperlinks->hyperlink as $hyperlink ) {
					$this->hyperlinks[ (string) $hyperlink['ref'] ] = (string) $hyperlink['display'];
				}
			}
			
			return $ws;
		} else {
			$this->error( 'Worksheet '.$worksheet_id.' not found.');
			return false;
		}
	}

Thanks!

**Comment by up2go-sschwarz** [comment]
Hi @shuchkin  why is this closed? after saving xlsx in libre, the script won't work for me.
```
if ( $xlsx = SimpleXLSX::parse($tmp_file) ) {
	print_r( $xlsx->rows() );
} else {
	echo SimpleXLSX::parse_error();
}
```
does not throw a message. just a blank page :(
Thanks for the work you have done! saved in excel it worked just perfect :)

**Comment by shuchkin** [comment]
ini_set('display_errors', true);
ini_set('error_reporting', true);
if ( $xlsx = SimpleXLSX::parse($tmp_file) ) {
	print_r( $xlsx->rows() );
} else {
	echo SimpleXLSX::parse_error();
}

**Comment by up2go-sschwarz** [comment]
thanks for your fast response, it didn't show any errors either, sorry. Were you able to read the `upload_template.xlsx` Kukulkano uploaded? I am not.

**Comment by shuchkin** [comment]
try

$xlsx = SimpleXLSX::parse('book.xlsx');
$first_id = key( $xlsx->sheetNames() );
print_r( $xlsx->rows( $first_id ) );

**Comment by up2go-sschwarz** [comment]
great, thank you, this worked! 💯  I don't really understand what these lines do, are you able to patch this? or can you provide me any if statement that tells me if the file is a Libre file?

**Comment by Kukulkano** [comment]
I'm also interested in a generic solution. It should be able to handle both Microsoft Excel and LibreOffice Calc saved xlsx files out of the box. If parsing the sheets solves the issue, maybe it can be done in general?

**Comment by up2go-sschwarz** [comment]
@Kukulkano It's fixed in the latest version 👍

**Comment by Kukulkano** [comment]
Oh, 9 days ago. Great! Thanks! :)
