### ISSUE TITLE
ERROR Request timedout after 30 seconds

### ISSUE THREAD

**Issue by maxcss** [shuchkin/simplexlsx#100]
Hi,

I have issue when parsing a file with 7 thousand + records. That xlsx just have 2 columns. 
I have tried to increase the time limit by adding "ini_set('max_execution_time', 300);" or "set_time_limit(300)" on top of my script but it's not working. Next, I even try to set the php.ini but still the same error comes out. So is there any ways I can increase the exception time when parsing a xlsx file? 

Thanks in advance.

MaxC

**Comment by shuchkin** [comment]
Which line is the timeout error triggered?
Pls enable debug https://github.com/shuchkin/simplexlsx#debug

**Comment by iprimaek** [comment]
Okay, you are right, it's the other thing that causing the timed out issue not SimpleXLSX...
Thanks for your support anyway.

**Comment by adiditm** [comment]
I'm using SimpeXLSXGen with about 200k++ records and got memory limited from PHP

Fatal error: Allowed memory size of 973078528 bytes exhausted (tried to allocate 72 bytes) in *.php on line 256

Is there any way to do direct write to file without saving data ti PHP array?

Thank You

**Comment by shuchkin** [comment]
pls use alternative library
