### ISSUE TITLE
Exception on internal hyperlink

### ISSUE THREAD

**Issue by dalbre** [shuchkin/simplexlsx#104]
Thanks for your great tool.

I am trying to read an xlsx file containing internal hyperlinks (i.e. a cell, when clicked, referring to another section of the spreadsheet).

Unfortunately, simplexlsx stumbles over those with a 'notice':

`Notice: Undefined index: in C:\xampp\subdomains\dirk\pages\aero\aircraft\SimpleXLSX.php on line 770`

It's actually not the the parse but the dimension statement that triggers this notice in the following simple code:

```
<?php
require_once 'SimpleXLSX.php';
$xlsx = SimpleXLSX::parse("C:\file.xlsx");
$dim = $xlsx->dimension(0); 
```

**Comment by shuchkin** [comment]
try 0.8.24
