### ISSUE TITLE
Read range of cells from page ?

### ISSUE THREAD

**Issue by MadTomT** [shuchkin/simplexlsx#107]
Hi,

Instead of reading the entire page is it possible to read all rows and columns between two cells ?
eg: B10 -  K50

So you would get allow rows and columns between those two cells ?

Thanks

**Comment by shuchkin** [comment]
```php
$result = array_slice( $xlsx->rows(), 10, 40);
```

**Comment by shuchkin** [comment]
very slow version of getRange() here
https://github.com/Jonowa/simplexlsx/blob/master/src/SimpleXLSX.php#L987
