### ISSUE TITLE
Start reading from specific row ?

### ISSUE THREAD

**Issue by MadTomT** [shuchkin/simplexlsx#108]
Hi

running `$rows = ( $xlsx->rows( 1) );` starts reading the worksheet from the first row down.

Would it be possible to only start reading at row x ?
Read from row 10 and ignore all above that ?
eg: 		`$rows = ( $xlsx->rows( 1, 10 ) );
`
Thanks

**Comment by shuchkin** [comment]
> running `$rows = ( $xlsx->rows( 1) );` starts reading the worksheet from the first row down.

rows(0) - read all from first sheet, rows(1) - read all from second sheet

try
```php
print_r( array_slice( $xlsx->rows(), 0, 10) );
```

**Comment by MadTomT** [comment]
Thanks for the reply.

I want to read from a worksheet, but start at row 10, not row 0 is that possible ?

**Comment by shuchkin** [comment]
Tom go to docs pls
https://www.php.net/manual/en/function.array-slice.php

**Comment by MadTomT** [comment]
Thanks.. makes sense.
