### ISSUE TITLE
Cell color - font and background

### ISSUE THREAD

**Issue by SvilenStoianov** [shuchkin/simplexlsx#109]
Hello,
Is there a way to retrieve cell font color and background color?

Thank you!

**Comment by shuchkin** [comment]
https://github.com/PHPOffice/PhpSpreadsheet

**Comment by vce-wabbott** [comment]
Hi Sergey - I see the styles (inclusive of fills: styles:SimpleXLSX:private]->fills) are retrieved via SimpleXLSX::parse but I don't see any way to map the cell to any of the styles. Any chance you would consider extending rowEX() to include the cell fill color or possibly the index to the cellFormats array? I would use PhpSpreadsheet but I have Excel file (attached) generated by EPPlus that causes errors upon $reader->load($xlsx_file)

[Portmap-P1182421-93171.xlsx](https://github.com/shuchkin/simplexlsx/files/7182756/Portmap-P1182421-93171.xlsx)

**Comment by shuchkin** [comment]
SimpleXLSX !== AdvancedXLSX

**Comment by shuchkin** [comment]
try 1.0.12
$xlsx->rowsEx() // return style and css now
$xlsx->toHTMLEx() return styled HTML table

**Comment by vce-wabbott** [comment]
I'll test it out and let you know how I make out.

**Comment by vce-wabbott** [comment]
The new rowsEx() enhancements are working well - thanks much for the improvements
