### ISSUE TITLE
Error on parse xlsx

### ISSUE THREAD

**Issue by Binapick** [shuchkin/simplexlsx#11]
I have download the new version 0.7.3, but it did not read the xlsx and give some errors:
if I use the old style:
```
$_xlsx = new SimpleXLSX('öbsv_results.xlsx');
if($_xlsx->success()){
}else{
echo 'xlsx error: '.$_xslx->error();
}
```
this error are shown:

> Notice: Undefined variable: _xslx in C:\xampp\htdocs\vhost\support.a-timing.wien\importParaResults.php on line 111
> Fatal error: Uncaught Error: Call to a member function error() on null in C:\xampp\htdocs\vhost\support.a-timing.wien\importParaResults.php:111 Stack trace: #0 {main} thrown in C:\xampp\htdocs\vhost\support.a-timing.wien\importParaResults.php on line 111

if I use the new one
```
$_xlsx = SimpleXLSX::parse('öbsv_results.xlsx');
print_r($_xlsx->rows(2));
```

> Fatal error: Uncaught Error: Call to a member function rows() on boolean in C:\xampp\htdocs\vhost\support.a-timing.wien\importParaResults.php:28 Stack trace: #0 {main} thrown in C:\xampp\htdocs\vhost\support.a-timing.wien\importParaResults.php on line 28

did you have any idea where my problem is?

**Comment by shuchkin** [comment]
$_xslx->error change to $_xlsx->error

**Comment by shuchkin** [comment]
new style
if ( $xlsx = SimpleXLSX::parse('file.xlsx') ) {  print_r( $xlsx->rows(2)); }

**Comment by Binapick** [comment]
I use now following lines:
```
if($xlsx = SimpleXLSX::parse('para_results.xlsx')){
	print '<pre>'; print_r( $_xlsx->rows(2) );print '</pre>';
}else{
	echo 'xlsx error: '.$xslx->error;
}
```
result:

> Notice: Undefined variable: xslx in C:\xampp\htdocs\vhost\support.a-timing.wien\importParaResults.php on line 33
>  Notice:
>  Trying to get property of non-object in C:\xampp\htdocs\vhost\support.a-timing.wien\importParaResults.php on line 33
> xlsx error: 

if I remove the error output $xlsx-error, I get no error and no output

**Comment by shuchkin** [comment]
fixed examples

try
if ( $xlsx = SimpleXLSX::parse('book.xlsx') ) {
	print_r( $xlsx->rows() );
} else {
	echo SimpleXLSX::parse_error();
}

**Comment by Binapick** [comment]
I get this now:
> Fatal error: Uncaught Error: Call to undefined method SimpleXLSX::parse_error() in C:\xampp\htdocs\vhost\support.a-timing.wien\importParaResults.php:33 Stack trace: #0 {main} thrown in C:\xampp\htdocs\vhost\support.a-timing.wien\importParaResults.php on line 33

**Comment by shuchkin** [comment]
update class before
