### ISSUE TITLE
Cell value has changed after parsing

### ISSUE THREAD

**Issue by jasperpoppe** [shuchkin/simplexlsx#110]
I have cells with values like "-6 ST" or "-8 M".

This is my code:
```
$xlsx = SimpleXLSX::parse('file.xlsx');
$rows = $xlsx->rows();
```

When I print `$rows`, the value of "-6 ST" has changed to "-6" (the "ST" is gone and type is a number)
and the value of "-8 M" has changed to "1899-12-22 00:00:00" (the "M" is gone and type is string).

I believe that this is a bug while parsing the cells in the Excel file.

In attachment, you'll find the example file where I found this bug.
Column "P" has these values I'm speaking of.

Thanks for checking my question.

[example.xlsx](https://github.com/shuchkin/simplexlsx/files/7034899/example.xlsx)

**Comment by shuchkin** [comment]
SimpleXSLX ignores formats.

try 0.8.26

use rowsEx()
check *format* for detection ST or M suffix

```php
$r = $xlsx->rowsEx();
print_r( $r[14][15] );
print_r( $r[15][15] );
```
```
Array
(
    [type] => 
    [name] => P15
    [value] => -1
    [href] => 
    [f] => 
    [format] => #,##0" ST";\-#,##0" ST";#,##0" ST";@
    [r] => 15
    [hidden] => 
)
Array
(
    [type] => 
    [name] => P16
    [value] => -8
    [href] => 
    [f] => 
    [format] => #,##0" M";\-#,##0" M";#,##0" M";@
    [r] => 16
    [hidden] => 
)
```

**Comment by jasperpoppe** [comment]
Thanks @shuchkin !

It's cool you can extend the cell info, but I just want every cell as a string. Is that even possible?
We don't see the "-8 M" as a number format.

**Comment by shuchkin** [comment]
use other lib
https://phpspreadsheet.readthedocs.io/en/latest/
