### ISSUE TITLE
Can't get Zero from value

### ISSUE THREAD

**Issue by RomaKandelaki** [shuchkin/simplexlsx#112]
Hi, first thank you for such a great work, it helped me a lot, but there is something I don't know how to fix. I'm getting values from xlsx which contains currency numbers (3.1112), but if one of them is ending with zero, I'm getting like this: 4.291 instead of 4.2910.
I'm storing this values into MySql database, so I do need to get correct value, any ideas how to fix?

**Comment by shuchkin** [comment]
try $xslx->towsEx()

or other lib
https://phpspreadsheet.readthedocs.io/en/latest/

**Comment by RomaKandelaki** [comment]
<b>Fatal error</b>:  Uncaught Error: Call to undefined method SimpleXLSX::towsEx()

**Comment by RomaKandelaki** [comment]
OK, problem is actually the excel file, since it is numeric row, it shows 4.2910 but actually it is 4.291
