### ISSUE TITLE
Formula Strings

### ISSUE THREAD

**Issue by vszgalaxy** [shuchkin/simplexlsx#118]
Hello,
My external xlsx contain strings but as formulas
="PLN"
="EUR"
etc..

SimpleXLSX::parse works fine, but these formulas return "0" string

How can i handle to get the correct values from these cells?

Thanks,

**Comment by shuchkin** [comment]
SimpleXLSX !== AdvancedXLSX, formulas ignored for now
try other php xlsx library

**Comment by shuchkin** [comment]
u can extract formula and calculate value in your code
