### ISSUE TITLE
error output

### ISSUE THREAD

**Issue by Binapick** [shuchkin/simplexlsx#12]
I get after use the Version 0.7.4
the following output:  

> xlsx error: xl/../customXml/item1.xml not found!
I did not understand this. Is that the message it can not found the file?

**Comment by shuchkin** [comment]
Y u tried load XML file? Use SimpleXLSX::pars( $filename) where $filename must be correct Excel 2007 .xlsx file

**Comment by Binapick** [comment]
No I load a excel 2016 file. with the Version 0.7.1 the load it, I did not understand the Problem. should I send you this file?

**Comment by shuchkin** [comment]
send me file to sergey,shuchkin@gmail.com

**Comment by shuchkin** [comment]
update 
https://github.com/shuchkin/simplexlsx/blob/master/simplexlsx.class.php

**Comment by Binapick** [comment]
Now it works thanks
