### ISSUE TITLE
Namespace definition in Class

### ISSUE THREAD

**Issue by BokuNoMaxi** [shuchkin/simplexlsx#121]
Hello dear developers,

is it possible to declare a namespace at top of your class? 
I am using your tool in a TYPO3 composer installation, so i would like to call your class like this: 

use Shuchkin\SimpleXLSX;
if ( $xlsx = SimpleXLSX::parse('book.xlsx') ) {
      print_r( $xlsx->rows() );
  } else {
      echo SimpleXLSX::parseError();
  }
  
  instead of: 
  require_once __DIR__.'/../src/SimpleXLSX.php';

**Comment by shuchkin** [comment]
try 0.9.10
