### ISSUE TITLE
Out of memory with rowsEx()

### ISSUE THREAD

**Issue by maxiben** [shuchkin/simplexlsx#122]
Hello,

I encounter a problem with the "simplexlsx" library on some xlsx file with the "rowsEx()" mode, this same file goes well with "rows()".

simplexlsx 0.8.32

PHP Fatal error:  Out of memory (allocated 344457216) (tried to allocate 36 bytes) on line 711

I can provide you with the excel file if needed.

cordially

**Comment by shuchkin** [comment]
https://help.dreamhost.com/hc/en-us/articles/214893937-How-do-I-increase-the-PHP-memory-limit-#:~:text=Increasing%20the%20PHP%20memory%20limit,than%20sufficient%20for%20most%20needs.

**Comment by maxiben** [comment]
Indeed i had to multiply the amount of memory by 3 compared to "rows()".

thinks.

**Comment by shuchkin** [comment]
try 1.0.12
foreach( $xlsx->readRowsEx() as $r ) {
  //
}

**Comment by maxiben** [comment]
OK, thinks but i have an error ( SimpleXLSX -> line 1072 ) with "readRowsEx()" :

        if (($ws = $this->worksheet($worksheetIndex)) === false) {
            **return null;**
        }

**Comment by shuchkin** [comment]
1.0.13

**Comment by maxiben** [comment]
PHP 5.5

PHP Fatal error:  Generators cannot return values using "return" in SimpleXLSX.php on line 1072

**Comment by shuchkin** [comment]
> PHP 5.5
> 
> PHP Fatal error: Generators cannot return values using "return" in SimpleXLSX.php on line 1072

fixed in 1.0.14

**Comment by maxiben** [comment]
great it works .. thank you
