### ISSUE TITLE
Symbol < in Table

### ISSUE THREAD

**Issue by yurets2011** [shuchkin/simplexlsx#126]
when the symbol < appears in the table
there is a problem with the generated array.

Table:

010347331193430721*f.X<XOZRuiVa
010347331198530921Fc'%A':<I'_;J
010347331196320821tAfd(+?MxO*tX

Parse:

    [16] => Array
        (
            [0] => 010347331193430721*f.X Array
        (
            [0] => 010347331198530921Fc'%A': Array
        (
            [0] => 010347331196320821tAfd(+?MxO*tX
        )

**Comment by shuchkin** [comment]
<img width="361" alt="Screenshot_282" src="https://user-images.githubusercontent.com/315872/157883079-8eaf9b2a-8d82-4a01-9852-7bfb302d4135.png">
<img width="612" alt="Screenshot_283" src="https://user-images.githubusercontent.com/315872/157883093-9d5392b0-71cc-406e-bb3d-59a46561323d.png">

Unzip and check xl/sharedStrings.xml
