### ISSUE TITLE
Get [format] cell

### ISSUE THREAD

**Issue by maxiben** [shuchkin/simplexlsx#127]
Hello,

since version 1.0.14, the formats cell no longer go up in the array.

Array
(
    [type] => 
    [name] => I1
    [value] => 0,42
    [href] => 
    [f] => 
    **[format] =>** 
    [s] => 8
    [css] => color: #000000;font-family: Calibri;font-size: 15px;text-align: center;
    [r] => 1
    [hidden] => 
    [width] => 15,28515625
    [height] => 0
)

Cordially.

**Comment by shuchkin** [comment]
pls send xlsx

**Comment by maxiben** [comment]
[Festool2022.xlsx](https://github.com/shuchkin/simplexlsx/files/8303524/Festool2022.xlsx)

col "S" and "T" for exemple.

**Comment by shuchkin** [comment]
fixed in 1.0.16
format = 0.00% there

**Comment by maxiben** [comment]
it works, great
