### ISSUE TITLE
column extraction from xlsx 

### ISSUE THREAD

**Issue by Miz-373** [shuchkin/simplexlsx#129]
Hello Mr.shuchkin,
i was wondering if i can extract a specific column to write it from xlsx to csv, insted of writing the whole (big size) xlsx file as csv, which will consume more time, processing and size.
i could not find a clear issue or example about that.
here is my code, which i am targeting the sheet number (11), and would like to get only two columns from it (1,23). 

if ($xlsx = SimpleXLSX::parse($xlsx_filepath))
	{
		$f = fopen($csv_filepath, 'wb');
		foreach ($xlsx->rows(11) as $r) 
		{
			fwrite($f, implode(',',$r) . PHP_EOL);
		}
		fclose($f);
	}
	else 
	{
		echo SimpleXLSX::parseError();
	}

**Comment by shuchkin** [comment]
use readRows()
https://github.com/shuchkin/simplexlsx#xlsx-read-huge-file-xlsx-to-csv

**Comment by Miz-373** [comment]
thanks for reply, i could not get it using readRows() as you mentioned.
but i could manage to add a line before to define the columns that i need, and it worked.
where $y= the two columns that i am targeting, and it worked just perfect. Thanks alot Sergey.
code:

foreach ($xlsx->rows(11) as $r)
{
       $y = [$r[1],$r[23]];
	fwrite($f, implode(',',$y) . PHP_EOL);
}
fclose($f);
