### ISSUE TITLE
False dimension?

### ISSUE THREAD

**Issue by greenreptile** [shuchkin/simplexlsx#130]
Hi

Recently I faced with below file that simplexlsx shows 1x1 dimension for it **but it has 2384 rows** :
[contact.xlsx](https://github.com/shuchkin/simplexlsx/files/8711456/contact.xlsx)

https://mega.nz/file/OsMAnTYB#pjgVMuAq2YwtJMCNgtZmteQIsI3cuf4okqZB_z7SK9c

I unzipped manually and checked sheet1.xml :
`<dimension ref="A1:A2383"/>`

Any idea?

**Comment by shuchkin** [comment]
simplexlx  removes empty lines, so the dimension becomes incorrect

**Comment by greenreptile** [comment]
Got the point, Thanks.
