### ISSUE TITLE
503 error when uploading a 4 mb excel file

### ISSUE THREAD

**Issue by jatindergit** [shuchkin/simplexlsx#134]
![image](https://user-images.githubusercontent.com/15045055/176986936-14e57004-869c-4579-bafb-2e7187081762.png)
Please help

**Comment by shuchkin** [comment]
https://github.com/shuchkin/simplexlsx#debug

**Comment by jatindergit** [comment]
I tried but did not display any error. After this I tried using other library but same error is coming
https://github.com/PHPOffice/PhpSpreadsheet/issues/2495

**Comment by shuchkin** [comment]
https://stackoverflow.com/questions/5127838/where-does-php-store-the-error-log-php-5-apache-fastcgi-and-cpanel

**Comment by shuchkin** [comment]
99% there memory error, see memory_limit
https://www.php.net/manual/en/ini.core.php#ini.memory-limit

**Comment by smartcodegames** [comment]
I had the same problem, but adjusting memory_limit was not helping, it did not even log a memory error. Finally I figured out that my PHP was too old! I upgraded from v5.6 to v7.4 and it worked fine even with a huge xlsx. So the lib is fine, thank you!!!
