### ISSUE TITLE
How do i get cell value without format?

### ISSUE THREAD

**Issue by akeans-mgs** [shuchkin/simplexlsx#138]
Hi,

I have cell values like 

- 100%
- 85%
- 78.99%

Need to get the exact value instead of formatted value.

Now I am getting values like

- 1
- 0.8
- 0.7889

**Comment by shuchkin** [comment]
85 / 100 = 0.85 :)

not sure, but try $xlsx->rowsEx()

**Comment by shuchkin** [comment]
`$v = ($r[3]*100) . '%';`

**Comment by akeans-mgs** [comment]
> $r[3

Where i have to add this

**Comment by shuchkin** [comment]
https://www.php.net/manual/ru/control-structures.foreach.php
