### ISSUE TITLE
error during import 20000 rows

### ISSUE THREAD

**Issue by mimcomp** [shuchkin/simplexlsx#14]
Hi,
I tried to import 20000 rows by excels to mysql database  but there are some issues during import : 

A PHP Error was encountered

Severity: Warning

Message: gmdate() expects parameter 2 to be integer, float given

Filename: controllers/simplexlsx.class.php

Line Number: 725

**Comment by shuchkin** [comment]
try actual version https://github.com/shuchkin/simplexlsx/blob/master/simplexlsx.class.php
