### ISSUE TITLE
Undefined index: alignment

### ISSUE THREAD

**Issue by DMGPage** [shuchkin/simplexlsx#141]
Hello! 
Working with your library, I encountered some issue:
> shuchkin/simplexlsx/src/SimpleXLSXEx.php:268
> Undefined index: alignment

I don't really know, how this file was made, but it always creates this error. I added example of the file in attachment.
[import_6391894ae8e46.xlsx](https://github.com/shuchkin/simplexlsx/files/10183082/import_6391894ae8e46.xlsx)

**Comment by DMGPage** [comment]
Just want to remind you, that issue still exists in version 1.0.19. Also I found out, that issue appears with files, created by Google Sheets.

**Comment by shuchkin** [comment]
fixed in master branch
