### ISSUE TITLE
date parse error

### ISSUE THREAD

**Issue by unxed** [shuchkin/simplexlsx#142]
File is exported from Google Spreadsheets. It has the only cell with date. Date is parsed as "23275" instead of "21.09.1963".

[bug sample.xlsx](https://github.com/shuchkin/simplexlsx/files/10580365/bug.sample.xlsx)

**Comment by shuchkin** [comment]
try [1.0.19](https://github.com/shuchkin/simplexlsx/releases/tag/1.0.19)

**Comment by unxed** [comment]
1963-09-21 now parsed as 1963-09-21 00:00:00
I think it's acceptable! thank you!
