### ISSUE TITLE
Unknown archive format 

### ISSUE THREAD

**Issue by CHANCENY** [shuchkin/simplexlsx#143]
Am trying to read excel file with .xlsx extension but am getting  Unknown archive format message please help

**Comment by shuchkin** [comment]
attach xlsx here or send sergey.shuchkin@gmail.com

**Comment by CHANCENY** [comment]
I got it now! problem was after change my file name somehow my file was corrupt couldn't even open in ms excel but downloading again the file without changing it name everything works fine but thank you for reaching out @shuchkin

**Comment by Vasiliy-Makogon** [comment]
> Прикрепите файл xlsx сюда или отправьте [на sergey.shuchkin@gmail.com](mailto:sergey.shuchkin@gmail.com)

Привет, вот пример проблемного файла

[Untitled 1.csv](https://github.com/user-attachments/files/24382036/Untitled.1.csv)

**Comment by shuchkin** [comment]
> > Прикрепите файл xlsx сюда или отправьте [на sergey.shuchkin@gmail.com](mailto:sergey.shuchkin@gmail.com)
> 
> Привет, вот пример проблемного файла
> 
> [Untitled 1.csv](https://github.com/user-attachments/files/24382036/Untitled.1.csv)

https://github.com/shuchkin/simplecsv
