### ISSUE TITLE
readRowsEx limit arg

### ISSUE THREAD

**Issue by trollwinner** [shuchkin/simplexlsx#146]
Hi there! Thank you for the library!

I believe there is an issue with the limit argument of the readRowsEx method. Much probably there should be a return instead of break on the 526th line.

**Comment by shuchkin** [comment]
```
foreach ($xlsx->readRowsEx() as $k => $r) {
    if ($k > 525) {
        break;
    }
    echo $r[0] . PHP_EOL;
}
```
