### ISSUE TITLE
dimension() returning array( 1, 1 ) regardless of file contents

### ISSUE THREAD

**Issue by celliso1** [shuchkin/simplexlsx#15]
dimension() does not report correct size for all files from this source (Neustar Port PS).

Example file provided.

[Portps_Search_Results (21).xlsx](https://github.com/shuchkin/simplexlsx/files/1395736/Portps_Search_Results.21.xlsx)

**Comment by shuchkin** [comment]
bad metadata in xml
u can read this data direct from xmldom:
print_r( $xlsx->worksheet(0)->dimension['ref'] ); // A1

skip dimension(), analize the rows() result
