### ISSUE TITLE
If the string in a cell contains a half-width English comma, it will be split into two cells.

### ISSUE THREAD

**Issue by langziyang** [shuchkin/simplexlsx#152]
when xlsx to csv file.
If the string in a cell contains a half-width English comma, it will be split into two cells.

![QQ截图20240329130728](https://github.com/shuchkin/simplexlsx/assets/2345387/750fc02c-af60-4850-b6e1-0be8d675d91b)
![2](https://github.com/shuchkin/simplexlsx/assets/2345387/c1aaf4c5-f368-4f7b-b1f6-0d4c76c5f1e6)

**Comment by langziyang** [comment]
Probably my problem

**Comment by langziyang** [comment]
Probably my problem

**Comment by shuchkin** [comment]
update example
https://github.com/shuchkin/simplexlsx?tab=readme-ov-file#xlsx-read-huge-file-xlsx-to-csv
