### ISSUE TITLE
The 'activeSheet' value is not set

### ISSUE THREAD

**Issue by bjkleier** [shuchkin/simplexlsx#153]
The 'reptile' code is not executed because a **`break`** exits the foreach loop after the workbook.xml content has been read.
I have tested the example "XLSX get sheet names and sheet indexes" with the "countries_and_population.xlsx" and the output is not as in the example. The value of activeSheet is 0 instead of 1.
My proposed solution:
move the code of '`// reptile hack :: find active sheet from workbook.xml`' before the **`break;`** (move line 505-510 in the source code to line 502).

 `

**Comment by shuchkin** [comment]
fixed in 1.0.20
