### ISSUE TITLE
Hyperlinks

### ISSUE THREAD

**Issue by Ondrashek** [shuchkin/simplexlsx#155]
if ( $xlsx = SimpleXLSX::parse('book.xlsx') ) {
    print_r( $xlsx->rows() );
} else {
    echo SimpleXLSX::parseError();
}

$xlsx->rows won't show hyperlink but only plain text. 

Can you add option to enable hyperlinks with url instead of plain text in classic parsing? 

Thanks :-)

**Comment by shuchkin** [comment]
https://github.com/shuchkin/simplexlsx?tab=readme-ov-file#using-rowsex-to-extract-cell-info

**Comment by Ondrashek** [comment]
Yes. This is working, but you must search in array because I used columns as keys so I can't find exact cell by id from ->rows().
