### ISSUE TITLE
Deprecated :  preg_replace(): Passing null to parameter #3  SimpleXLSX.php on line 927

### ISSUE THREAD

**Issue by mydevc** [shuchkin/simplexlsx#157]
<b>Deprecated</b>
:  preg_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in <b>/mnt/hgfs/project/m.xhkao.com/vendor/shuchkin/simplexlsx/src/SimpleXLSX.php</b>
on line <b>927</b>

**Comment by mydevc** [comment]
Suggested modification:
if (preg_match('/[mM]/', preg_replace('/\"[^"]+\"/', '', $format ?? ''))) { // [mm]onth,AM|PM

**Comment by shuchkin** [comment]
fixed in 1.1.11

**Comment by mydevc** [comment]
thanks
