### ISSUE TITLE
Merged Cells

### ISSUE THREAD

**Issue by syntxerr** [shuchkin/simplexlsx#160]
Is there a simple way to react to merged cells based on the data available in the xlsx files rather the iterating line by line? 

IE I have 
NAME --- Value 1 --- Value 2
*   - Value 1 --- Value 2
*   - Value 1 --- Value 2

Rather then saving the previous row, comparing if col 1 is empty then using the value from the row above if we can just fill the merged cells using the merged cells pointers from the data file?

**Comment by shuchkin** [comment]
```php
$data[0][0] = 'Name';
$data[0][1] = 'Value';
$data[1][1] = 'Value2';
$data[2][1] = 'Value3';
```
