### ISSUE TITLE
file parsed incorrectly

### ISSUE THREAD

**Issue by unxed** [shuchkin/simplexlsx#161]
[Паспорт Отделений 12.11.2024.xlsx](https://github.com/user-attachments/files/17754511/12.11.2024.xlsx)

**Comment by unxed** [comment]
The file should be read as an array of data, with each row containing colls:
- address
- code
- geographic coordinates.
 
However, I'm receiving lines with the region name in the first column, the city name in the second, and the third column empty. If I open this file in LibreOffice and save it under a different name, it is processed correctly.

**Comment by shuchkin** [comment]
There hidden sheets, use ```print_r($xlsx->rows(2));```

![Снимок экрана 2024-11-15 002731](https://github.com/user-attachments/assets/ec26bb23-2f46-4df3-8148-bab113c0ce79)

https://opencollective.com/simplexlsx

**Comment by unxed** [comment]
Thanks!

**Comment by unxed** [comment]
Is there any way do detect hidden sheets presence and skip them automatically?

**Comment by shuchkin** [comment]
Of course not, this will break the logic of reading data from the book
