### ISSUE TITLE
getting a date instead of string

### ISSUE THREAD

**Issue by CereEnder** [shuchkin/simplexlsx#17]
Hello, I have a problem.
This is the input (and the output expected), and the current output.
It should be returned as is, but date returned.
Thank you!

<img src="https://i.imgur.com/w6lGW8E.png"/>

<img src="https://i.imgur.com/MJyzHMM.png"/>

**Comment by CereEnder** [comment]
nvm, columns where formatted by number or  general type. 
Changed to string: worked
thank you.

Closed.

**Comment by shuchkin** [comment]
ok
