### ISSUE TITLE
Not reading Google Analytics report sheet names

### ISSUE THREAD

**Issue by TitaniumCreative** [shuchkin/simplexlsx#18]
I have downloaded a report from google analytics and it seems to be having issues reading the sheet names. It only returns the last sheet name and assigns the index as 0.

There are three sheets and I am only able to read the first one.

If I delete the first sheet, it will read the other to with ->rows(1) and ->rows(2) but still will not read the sheet names properly.

I have attached the file as it was downloaded.

I had previously uploaded an edited version of the spreadsheet. This is the unedited version.

[Analytics Resaling Shop Pages 20180101-20180131.xlsx](https://github.com/shuchkin/simplexlsx/files/1720287/Analytics.Resaling.Shop.Pages.20180101-20180131.xlsx)

**Comment by shuchkin** [comment]
try 0.7.9 https://github.com/shuchkin/simplexlsx/blob/master/simplexlsx.class.php
