### ISSUE TITLE
Missing license information

### ISSUE THREAD

**Issue by Kukulkano** [shuchkin/simplexlsx#2]
Hi. Just wondering if I can use this in a commercial project? But I found no license information. Is it LGPL or similar or just free? Best if this would be added to the source-code (some header comment information).

**Comment by shuchkin** [comment]
license added
https://github.com/shuchkin/simplexlsx




> Hi. Just wondering if I can use this in a commercial project? But I
> found no license information. Is it LGPL or similar or just free?
> Best if this would be added to the source-code (some header comment information).
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
>   
>     
> {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/shuchkin/simplexlsx","title":"shuchkin/simplexlsx","subtitle":"GitHub
> repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open
> in
> GitHub","url":"https://github.com/shuchkin/simplexlsx"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Missing
> license information (#2)"}],"action":{"name":"View
> Issue","url":"https://github.com/shuchkin/simplexlsx/issues/2"}}} 



-- 
Thank You
Sergey
http://www.sibvision.ru/
http://www.smspilot.ru/
https://twitter.com/shuchkin
https://www.facebook.com/shuchkin

**Comment by Kukulkano** [comment]
That was fast, THANK YOU!
