### ISSUE TITLE
Lines inserted before are not considered by SimpleXLSX

### ISSUE THREAD

**Issue by vmorreel** [shuchkin/simplexlsx#23]
Hi,
I guess I found an issue about the lib. I'm reading .xlsx file with a beginning line given (here its 15) because there isn't data before line 15. And when i'm reading the file with the lib, the first data read (which is on line 15 when I open the file manually) are detected on line 12 when debugging.

I can reproduce the issue. This is when you insert lines (with Excel, right-click on the index column at left and Insert).
I can add tons of lines before, the data will always be read at line 12.

Is there an issue to this issue ? Or if not, can you fix it ?

Thanks & thanks for this weightless lib !

**Comment by shuchkin** [comment]
send me your xlsx to sergey.shuchkin@gmail.com and your code for reading

**Comment by vmorreel** [comment]
This will be hard because the code is in an entire project.
I need to anonymize the data and to refactor the code to send it to you. 
I will recontact you as soon as I finished the refactoring.

Thank you

**Comment by vmorreel** [comment]
Send!

**Comment by shuchkin** [comment]
don't trust meta info
just ignore empty rows

```
foreach( $xlsx->rows() as $r ) {
	if ( $r[0] !== '' ) {
		var_dump( $r );
	}
}

// or

foreach( $xlsx->rows() as $r ) {
	if ( is_numeric( $r[0]) ) {
		var_dump( $r );
	}
}
```

**Comment by vmorreel** [comment]
Hi again Sergei, and thanks for the answer.

But in fact, this doesn't solved the problem. Because there could be data before the line 15 but I need to ignore them until I'm at line 15.

Your solution is to ignore if its empty, but for exmaple in my file, I don't need the line with headers ("VOL", "COND", etc...)

The final goal with this project is to permit to user to build "import templates" and then select a template, a file corresponding to the template and get the data from it.
But some data aren't usefull and i need to read at a specific given line.

In the end, the tool will not be used by me but by users. And it could be multiple different files...

**Comment by shuchkin** [comment]
update class
https://github.com/shuchkin/simplexlsx/blob/master/simplexlsx.class.php

try $xlsx->rowsEx()

u need real row index "r" in cell info
```
$r[0] array (size=7)
      'type' => string '' (length=0)
      'name' => string 'A1' (length=2)
      'value' => string '' (length=0)
      'href' => string '' (length=0)
      'f' => string '' (length=0)
      'format' => string '' (length=0)
      'r' => int 4
```

see example

```
foreach( $xlsx->rowsEx() as $r ) {
  if ( $r[0]['r'] < 15) { continue; }
}
```

**Comment by vmorreel** [comment]
**You're da best.**

Thanks a lot for the patch ! It works **perfectly** !
