### ISSUE TITLE
Percentage data parse divided by 100

### ISSUE THREAD

**Issue by phoxer** [shuchkin/simplexlsx#26]
Hello, I am having this problem, when wanting to read data of percentages, is returned to me divided by 100, for example if I have a cell with 17.34% I am receiving 0.17 as data read.

How could I get the real value of the cell? when it is of type percentage.

Is not a solution the multiplication by 100 but, because some extra data is missed, for exemple de float data.

Thanks.

**Comment by phoxer** [comment]
Thanks, that was a solution :)

**Comment by shuchkin** [comment]
np
