### ISSUE TITLE
Sheet Id and rows Error

### ISSUE THREAD

**Issue by spAnser** [shuchkin/simplexlsx#28]
So after a bit of debugging.

I have determined that the `sheetNames()` function returns ids and names. However using those ids to get the rows can return the incorrect sheet. if the spreadsheet has the sheets reordered. Asking for rows is not grabbing the matching sheet id but the sheet in the order of how they are sorted.

So if I made

Sheet 1
Sheet 2
Sheet 3

Then I reordered them before saving to

Sheet 2
Sheet 3
Sheet 1

Asking for sheet names with SimpleXLSX would return

2 => Sheet 2
3 => Sheet 3
1 => Sheet 1

But when I asked for `->rows(1)` which is the id for Sheet 1

I am getting back values from Sheet 2 since it is the first in the array.

**Comment by shuchkin** [comment]
Try [0.7.12](https://github.com/shuchkin/simplexlsx), I changed IDs to Indexes

**Comment by spAnser** [comment]
The new sheet index seems to always return false.

**Comment by shuchkin** [comment]
oops, try [0.7.13](https://github.com/shuchkin/simplexlsx)

**Comment by spAnser** [comment]
It looks like things are working fine.
