### ISSUE TITLE
500 Internal server error

### ISSUE THREAD

**Issue by giosal** [shuchkin/simplexlsx#29]
Hi, I'm getting a strange 500 internal server error while using your library.

I have several files with the data from a system, all of them in the same format. Some of them open without any problem, others return error 500.

Can I send the files to you? Or you can just download for example here http://np04-slow-control.web.cern.ch/np04-slow-control/app/data/Monitoring_18_08_08_Merge.XLSX which is giving the error. The file Monitoring_18_08_10_Merge.XLSX is read without any problem.

Thanks in advance

**Comment by shuchkin** [comment]
http://php.net/manual/ru/function.set-time-limit.php

**Comment by giosal** [comment]
Ok, this did help a lot! Thank you. I have just a quick question - how would I get values from a specific column only?

**Comment by shuchkin** [comment]
```
$xlsx = SimpleXLSX::parse('data.xlsx');
foreach ( $xlsx->rows() as $r ) {
  echo $r[0]."\r\n"; // out data from 1 col
}
```

**Comment by giosal** [comment]
ok, thanks a lot! issue solved by raisin the mem_limit and time_limit
