### ISSUE TITLE
gmdate() expects parameter 2 to be integer, float given in SimpleXLSX.php on line 868

### ISSUE THREAD

**Issue by urshar** [shuchkin/simplexlsx#33]
I have this issue with the import of an Excel 2016 Sheet again.

Warning: gmdate() expects parameter 2 to be integer, float given in ...\SimpleXLSX.php on line 868
Warning: gmdate() expects parameter 2 to be integer, float given in ...\SimpleXLSX.php on line 868

The warning comes two times. I'am not sure why this warning comes again.

use PHP 7.2 and simpleXLSX 0.8.3
Andreas

**Comment by shuchkin** [comment]
send me your xlsx sergey.shuchkin@gmail.com

**Comment by shuchkin** [comment]
fixed
