### ISSUE TITLE
Installation with composer

### ISSUE THREAD

**Issue by ingeJulianLasso** [shuchkin/simplexlsx#38]
First I want to give thanks for such a wonderful tool.

I would like to make a small comment about the installation of the library by means of composer.
```
composer require shuchkin/simplexlsx
```
The previous line does not work properly, for it to work it must be installed as follows:
```
composer require shuchkin/simplexlsx:dev-master
```
Is it possible to fix that?

Thank you for your time and dedication.

**Comment by geemeetheway** [comment]
I can't install it with : 
`
composer require shuchkin/simplexlsx

  [InvalidArgumentException]
  Could not find package shuchkin/simplexlsx at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability
`

**Comment by shuchkin** [comment]
fixed
added tag 0.8.5
thx
