### ISSUE TITLE
[date] simplexlsx wrong read date format

### ISSUE THREAD

**Issue by apple-idn** [shuchkin/simplexlsx#40]
Specification
OS = OSX 10.14.4
Excel 2019
<img width="111" alt="file input" src="https://user-images.githubusercontent.com/33564576/56132969-ec559480-5fbd-11e9-9342-9172758eb4fb.png">
file input
<img width="256" alt="output" src="https://user-images.githubusercontent.com/33564576/56132983-f7a8c000-5fbd-11e9-930c-e2ae1fe50d33.png">
Output

**Comment by shuchkin** [comment]
send me your xlsx to sergey.shuchkin@gmail.com

**Comment by shuchkin** [comment]
and try a rowsEx(), what are raw values there?

**Comment by apple-idn** [comment]
thanks very much @shuchkin I am email your

**Comment by shuchkin** [comment]
1900/1904 datetime system
https://bettersolutions.com/excel/dates-times/1904-date-system.htm

fixed in 0.8.6

**Comment by apple-idn** [comment]
@shuchkin thank very much you for your prompt fast  response and always supportive simplexlsx,

**Comment by shuchkin** [comment]
np

**Comment by direct4d** [comment]
Appeared again in 0.8.19...
