### ISSUE TITLE
Parsing error

### ISSUE THREAD

**Issue by Vladimir1247** [shuchkin/simplexlsx#41]
Parsing error found: value of data[1][0] must be at data[2][0]. Fix it, please.

![418114127](https://user-images.githubusercontent.com/49750519/56352846-c1935800-61d8-11e9-848f-aa80f932f627.jpg)
[084214.xlsx](https://github.com/shuchkin/simplexlsx/files/3093794/084214.xlsx)

**Comment by shuchkin** [comment]
там скорее всего вертикальное объединение ячеек, я его нехочу пока добавлять

**Comment by shuchkin** [comment]
а нет, условие было неточное - исправил в 0.8.7

**Comment by Vladimir1247** [comment]
Отлично, спасибо, сейчас обновлюсь - проверю

**Comment by Vladimir1247** [comment]
Да, все отлично, только composer не стал обновлять, пришлось вручную. Спасибо еще раз!
