### ISSUE TITLE
Date formated on user end but put string in

### ISSUE THREAD

**Issue by mcpalmer1328** [shuchkin/simplexlsx#43]
hoping you can help me figure something out for a client
they have a column in xlsx file that contains both date and string but in excel the column is formatted as date so appears when open in excel as 
6 weeks
8/20/2019
12 weeks
8 weeks

when i import using
$xlsx = new SimpleXLSX('QuoteUpdate.xlsx');
list($num_cols, $num_rows) = $xlsx->dimension();
        $f = 0;
        foreach ($xlsx->rows() as $r) {...
	else {
                                    if ($i == 10) {
                                        $date_due = $r[$i];
                                    } }
it changes the text ( 6 weeks) into date format (2019-1-24) i tried $date_due2=(string)($date_due); but still gives me the date ..thoughts. the file comes from an outside source so i cant have them change the formatting

**Comment by shuchkin** [comment]
Extended date formating is not supported, but u can try ->rowsEx to extract raw date value
and calculate weeks in PHP
https://github.com/shuchkin/simplexlsx/blob/master/examples/02-rows_and_rowsEx.php

**Comment by shuchkin** [comment]
$xlsx->datetimeFormat = false;
$xlsx->getCell(0, 'A1'); // float Excel date
$xlsx->unixtimestamp( $xlsx->getCell(0, 'A1'); // int seconds from 1 jan 1970

**Comment by mcpalmer1328** [comment]
i was able to use the excel date feature then $UNIX_DATE = ($date_due - 25569) * 86400; but i will try your latest thought for efficiency
