### ISSUE TITLE
PHP 7.4 Possible Backward Incompatible

### ISSUE THREAD

**Issue by dictosistemas** [shuchkin/simplexlsx#45]
Hi Sergey!

First of all, thanks for the great job with SimpleXLSX.
The PHP team released the new PHP 7.4.0 Alpha 1.
I was reading the "Backward Incompatible Changes" item, and I think there is a point of concern for SimpleXLSX.

Please access the link below:
https://github.com/php/php-src/blob/php-7.4.0alpha1/UPGRADING

The "1. Backward Incompatible Changes" -> "- Core:" ->
"  . Passing the result of a (non-reference) list() assignment by reference is
    consistently disallowed now. Previously this worked if the right hand side
    was a simple (CV) variable and did not occur as part of the list()."

Do you think is there any impact in SimpleXLSX code?

Thanks!

**Comment by shuchkin** [comment]
thx, bro
list() removed in 0.8.8

**Comment by dictosistemas** [comment]
Hi Sergey!
Thanks for the quick response.
Let me ask you:
I am using this code in my aplication:

 require_once('SimpleXLSX.php');
 $xlsx = new SimpleXLSX($tmpxls);
 list($num_cols, $num_rows) = $xlsx->dimension();
 foreach( $xlsx->rows() as $r ){
  //Do things....
 }

What do you recommend me to change?

Thanks a lot!

**Comment by shuchkin** [comment]
$dim = $xlsx->dimension();
	$num_cols = $dim[0];
	$num_rows = $dim[1];

**Comment by dictosistemas** [comment]
Thank you so much!

**Comment by shuchkin** [comment]
np
