### ISSUE TITLE
Wrong version v0.8.7 despite stating v.0.8.8

### ISSUE THREAD

**Issue by MetaCrawler** [shuchkin/simplexlsx#46]
Hey! 
First of all thank you very much for the great work. 
I have installed the package through composer and it is stating that v.0.8.8 was installed, 
but the SimpleXLSX class has still version v.0.8.7... 

composer show shuchkin/simplexlsx states:
![grafik](https://user-images.githubusercontent.com/7521898/61287252-c611e180-a7c4-11e9-9d25-c443c5b145d6.png)

But the SimpleXLSX is still: 
![grafik](https://user-images.githubusercontent.com/7521898/61287087-73382a00-a7c4-11e9-964e-933b6ce6f921.png)

You can also reproduce this also when you download the .ZIP for release 0.8.8. The .ZIP also contains SimpleXLSX 0.8.7. 

Best regards

**Comment by shuchkin** [comment]
fixed in 0.8.9
