### ISSUE TITLE
How to use SimpleXlsx on WordPress ?

### ISSUE THREAD

**Issue by anhhtz** [shuchkin/simplexlsx#50]
Hi,

I want to read some data from excel files (xlsx), analyze and insert into database on a WordPress site.

I don't know how to include SimpleXlsx without use composer ?

Hope give me some advises.

Thanks !

**Comment by shuchkin** [comment]
![Screenshot_65](https://user-images.githubusercontent.com/315872/65683179-70886980-e07e-11e9-8567-13aefed8a79f.jpg)
