### ISSUE TITLE
http://schemas.openxmlformats.org not working anymore

### ISSUE THREAD

**Issue by allull** [shuchkin/simplexlsx#51]
const SCHEMA_OFFICEDOCUMENT  =  'http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument';
	const SCHEMA_RELATIONSHIP  =  'http://schemas.openxmlformats.org/package/2006/relationships';
	const SCHEMA_SHAREDSTRINGS =  'http://schemas.openxmlformats.org/officeDocument/2006/relationships/sharedStrings';
	const SCHEMA_WORKSHEETRELATION =  'http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet';

The website used to get those constants values seems not to be working anymore.

**Comment by shuchkin** [comment]
just take it as ID-string
