### ISSUE TITLE
great lib!

### ISSUE THREAD

**Issue by gareth-ib** [shuchkin/simplexlsx#52]
Thanks for making this, definitely saved the day!

I don't know if it's possible, but it would be nice if you could make it parse the rows of the file incrementally, so you could cycle threw it line by line till it's empty instead of the giant parse at one time. Probably better for memory issues on potentially too large files

Thanks!

**Comment by shuchkin** [comment]
simplexml is fastest way, line by line or regex parse lead to dramatic perfomance down
