### ISSUE TITLE
Convert XLSX to CSV with UTF 8 characters

### ISSUE THREAD

**Issue by patrickmau** [shuchkin/simplexlsx#53]
I have an XLSX file I need to convert to CSV via the code below, however, at times this file contains chinese, japanese and korean characters which get lost in the conversion process.
How can I convert to CSV but keep the UTF8 characters intact?
`
// convert from XLSX to CSV
print ("XLSX file found, starting conversion to CSV<br>");
include '../../plugins/simplexlsx/simplexlsx.class.php';

$file_csv = $newfilename.'.csv';        // imported filename + .csv
$xlsx = new SimpleXLSX('./attachments/temp/'.$newfilename);

// convert file and move to property attachment folder
$fp = fopen('./attachments/'.$hotel_code.'/'.$file_csv, 'w');
foreach( $xlsx->rows() as $fields ) {
    fputcsv( $fp, $fields);
}
fclose($fp);
print ("XLSX file has been converted to CSV and moved to property attachment folder.<br>");`

**Comment by shuchkin** [comment]
simplexlsx has valid unicode support, check your csv viewer/reader
