### ISSUE TITLE
 DateTime issue

### ISSUE THREAD

**Issue by philippevincke** [shuchkin/simplexlsx#54]
Hi, a small question about time fields in the excel file.
In the file there are cells formatted as date (dd/mm/yyyy) and cells formatted as time (hh:mm).
Returning the date is no problem. Returning the time is not good. The class just returns '01/01/1970' which is a excel default date.
Is there a way to work around this issue ?
Thanks in advance.

**Comment by shuchkin** [comment]
see datetime examples
 https://github.com/shuchkin/simplexlsx#datetime-helpers
