### ISSUE TITLE
Saving xlsx from Apple Numbers...

### ISSUE THREAD

**Issue by fordero21** [shuchkin/simplexlsx#55]
Great library! I've noticed however if you edit or create a spreadsheet using Apple Numbers and save as an xlsx it doesn't appear to be able to read the spreadsheet. For whatever reason it causes a fatal error in PHP exhausting available memory (set to 1024MB in PHP which is huge!).

I've tested this and can reproduce the issue. I'm guessing that it's Numbers not converting the binary data correctly and causing the spreadsheet to be "unreadable" and hits an infinite loop.

**Comment by shuchkin** [comment]
Hello,

send me your xlsx

> Great library! I've noticed however if you edit or create a
> spreadsheet using Apple Numbers and save as an xlsx it doesn't
> appear to be able to read the spreadsheet. For whatever reason it
> causes a fatal error in PHP exhausting available memory (set to 1024MB in PHP which is huge!).
> I've tested this and can reproduce the issue. I'm guessing that
> it's Numbers not converting the binary data correctly and causing
> the spreadsheet to be "unreadable" and hits an infinite loop.
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> [ { "@context": "http://schema.org", "@type": "EmailMessage",
> "potentialAction": { "@type": "ViewAction", "target":
> "https://github.com/shuchkin/simplexlsx/issues/55?email_source=notifications\u0026email_token=AACNDYH2KA5PXD4SS26EM7DQQF7JJA5CNFSM4JESP6P2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4HUCTFPQ",
> "url":
> "https://github.com/shuchkin/simplexlsx/issues/55?email_source=notifications\u0026email_token=AACNDYH2KA5PXD4SS26EM7DQQF7JJA5CNFSM4JESP6P2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4HUCTFPQ",
> "name": "View Issue" }, "description": "View this Issue on GitHub",
> "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } } ]



-- 
Thank You
Sergey
http://www.sibvision.ru/
http://www.smspilot.ru/
https://twitter.com/shuchkin
https://www.facebook.com/shuchkin

**Comment by fordero21** [comment]
Hi Shuchkin,
Here's a spreadsheet exported from numbers as an Excel file (.xlsx). The library cannot read the file, however if you open it in Excel and re-save it then it can be read. I suspect that Numbers is causing an issue with the underlying file format.

Thanks!
[example.xlsx](https://github.com/shuchkin/simplexlsx/files/3828954/example.xlsx)

**Comment by shuchkin** [comment]
fixed skipEmptyRows,
rebuilt 0.8.10 try it
