### ISSUE TITLE
Potential code updates

### ISSUE THREAD

**Issue by a-bakos** [shuchkin/simplexlsx#57]
Hi Sergey,

First of all, I love this little piece of software that you created. The other day I was looking for a PHP solution to read Excel files and found yours, easy to use, and it just works.

I'd love to do some further work on it with you if you agree. I've got a few potential improvement ideas in mind. No major refactoring for now, but some modernisation if you will. Namely:
- Since PHP7 is now the standard, we could update the code to follow the new syntax
- I'd also love to make the code styling more consistent, like the use of whitespaces
- And the documentation could do with a little upgrading as well

What do you say, am I okay to proceed with these? I am thinking of doing the updates in relatively smaller chunks and commits, so you can review, merge, or reject them more easily.
Or if you have a different method, I'm up for it. Let me know what you think.

**Comment by shuchkin** [comment]
PHP7 syntax + tabs2spaces planed in 0.9
I will be grateful for the changes in readme.md - my native Russian language

**Comment by shuchkin** [comment]
1.0.12
