### ISSUE TITLE
0.9

### ISSUE THREAD

**Issue by shuchkin** [shuchkin/simplexlsx#58]
PHP7
tabs2spaces
remove file operations from __constructor
update: parseFile & parseData helpers ( added 0.8.13 )
updated: + Namespaces
updated: + xlsx comment reader (example below )

hey, make suggestions

**Comment by bimimicah** [comment]
Is it possible, please, to hold off on moving to anything PHP7 _exclusive_? While php.org doesn't support PHP5 anymore, enterprise users on RHEL and CentOS still get PHP5 support & patches for quite a while (years), so anything that breaks compatibility with PHP5 means we will have to maintain our own fork :(
Thank you for considering this idea.

**Comment by shuchkin** [comment]
Scratching my beard...

**Comment by chriseilander** [comment]
Namespaces are a must have

**Comment by giuliovale** [comment]
Please add comments reader

**Comment by shuchkin** [comment]
> Please add comments reader

u can parse comment XML direct right now

```php
$xlsx = SimpleXLSX::parse('xlsx/comment.xlsx' );
$comments = [];
if ( $comxml = $xlsx->getEntryXML( 'xl/comments1.xml' ) ) {
	foreach ( $comxml->commentList->comment as $com ) {
//		print_r ($com);
		$t = '';
		foreach( $com->text->r as $r ) {
			$rt = trim( $r->t );
			$t .= ( $t === '' ) ? $rt : "\r\n".$rt;
		}
		$comments[ (string) $com['ref'] ] = $rt;
	} 
}
print_r( $comments );
```
```
Array
(
    [A2] => Serg:
Дата в формате ДД.ММ.ГГГГ
    [D2] => Serg:
А это многострочная строка
Вторая строка
Третья строка
)
```

**Comment by giuliovale** [comment]
Thanks for reply

**Comment by shuchkin** [comment]
0.8.13
if ( $xlsx = SimpleXLSX::parseFile( $filename ) ) { }
if ( $xlsx = SimpleXLSX::parseData( $data ) ) { }

**Comment by TinouWild** [comment]
Is it possible to parse only those lines that are not hidden in the XLS?

**Comment by shuchkin** [comment]
> Is it possible to parse only those lines that are not hidden in the XLS? Thanks

what do u mean? show an example plz

**Comment by TinouWild** [comment]
> > Is it possible to parse only those lines that are not hidden in the XLS? Thanks
> 
> what do u mean? show an example plz

In XLS file you can hide some lines, so these lines are not visible. To hide lines in XLS, you can select any line and right click on it to mask. 

When i parse my file with your library, hidden lines are still parsed. 
I try to use rowsEx() but i don't have the visibility of the line (mask or not). Can you planned any option to parse only visible lines ?

**Comment by shuchkin** [comment]
> > > Is it possible to parse only those lines that are not hidden in the XLS? Thanks
> > 
> > 
> > what do u mean? show an example plz
> 
> In XLS file you can hide some lines, so these lines are not visible. To hide lines in XLS, you can select any line and right click on it to mask.
> 
> When i parse my file with your library, hidden lines are still parsed.
> I try to use rowsEx() but i don't have the visibility of the line (mask or not). Can you planned any option to parse only visible lines ?

try 0.8.25 ::rowsEx

**Comment by TinouWild** [comment]
[integ_test_pro.xlsx](https://github.com/shuchkin/simplexlsx/files/6893834/integ_test_pro.xlsx)

Thanks for your reactivity ! I update my composer but hidden is always at true. You can have an example with the file. Row 2 to 5 are hidden. 

In my case, it would be very useful to have a rowVisible() which would return only the visible lines of the file.

**Comment by shuchkin** [comment]
> [integ_test_pro.xlsx](https://github.com/shuchkin/simplexlsx/files/6893834/integ_test_pro.xlsx)
> 
> Thanks for your reactivity ! I update my composer but hidden is always at true. You can have an example with the file. Row 2 to 5 are hidden.
> 
> In my case, it would be very useful to have a rowVisible() which would return only the visible lines of the file.

fixed

rows() - fastest way to extract all data, covered 99% tasks
other meta info u can extract via slow&fat method rowsEx()
rowVisible() not needed, i don't want extra code in class

**Comment by sehrun** [comment]
add retrieving background with this probably
`SimpleXLSX.php` since line 757 to 
```		
				if ( $s > 0 && isset( $this->cellFormats[ $s ] ) ) {
					$format = $this->cellFormats[ $s ]['format'];
					$fillID = (int)$this->cellFormats[ $s ]['fillId'];
					$fill = @(string)$this->styles->fills->fill[$fillID]->patternFill->fgColor->attributes()->rgb;				
				} else {
					$format = '';
				}
				if (strlen($fill) == 8) {
					$fill = substr($fill, 2, 6);
				}
				$rows[ $curR ][ $curC ] = array(
					'type'   => $t,
					'name'   => (string) $c['r'],
					'value'  => $this->value( $c ),
					'href'   => $this->href( $c ),
					'f'      => (string) $c->f,
					'format' => $format,
					'r' => $r_idx,
					'bg'   => $fill
				);
```

**Comment by sehrun** [comment]
Yes, it doesn't work in that case. Still it would be very nice to have an ability to retrieve cell's background. I currenlty use the code above. Hopefully someone can develop it further.

**Comment by shuchkin** [comment]
try 1.0.12 
https://opencollective.com/simplexlsx/updates/simplexlsx-1-0-memory-and-styles
