### ISSUE TITLE
have a read error

### ISSUE THREAD

**Issue by mansour161** [shuchkin/simplexlsx#60]
hi 
this lib have an error 'to red 
i have two file and i attach them 
one of them which have a same rows, its OK 
but one of them, 3 rows in the first have not correct  , its not OK  and when i read  this file  and wana to show or save in database dos not work 
i attach two files
[this is correct.xlsx](https://github.com/shuchkin/simplexlsx/files/4012901/this.is.correct.xlsx)
[this is not correct.xlsx](https://github.com/shuchkin/simplexlsx/files/4012903/this.is.not.correct.xlsx)

thanks

**Comment by shuchkin** [comment]
use $skip_empty_rows param

```php
	echo '<style>table, th, td {
	  border: 1px solid black;
	}</style>';
	if ( $xlsx = SimpleXLSX::parse('xlsx/this.is.correct.xlsx', false, false, true ) ) {
		
		echo $xlsx->toHTML();
	} else {
		echo SimpleXLSX::parseError();
	}
	if ( $xlsx = SimpleXLSX::parse('xlsx/this.is.not.correct.xlsx', false, false, true ) ) {
		echo $xlsx->toHTML();
	} else {
		echo SimpleXLSX::parseError();
	}
```
![Screenshot_200](https://user-images.githubusercontent.com/315872/71635165-50071700-2c4c-11ea-9c80-e7dea232d06c.jpg)

**Comment by mansour161** [comment]
hi 
thank for your helping 
but i use this code and gives me this error for both of them (show and save)

((XML-entry not found /xl/workbook.xml))

and do not shwo to me  
im using from SimpleXLSX php class v0.8.10


	echo '<style>table, th, td {
	  border: 1px solid black;
	}</style>';
	if ( $xlsx = SimpleXLSX::parse('xlsx/this.is.correct.xlsx', false, false, true ) ) {
		echo $xlsx->toHTML();
	} else {
		echo SimpleXLSX::parseError();
	}


    if ( $xlsx = SimpleXLSX::parse('xlsx/this.is.correct.xlsx', false, false, true ) ) {
    try {
       $conn = new PDO( "mysql:host=localhost;dbname=saveecxel", "saveecxel", "",  array(PDO::MYSQL_ATTR_INIT_COMMAND => "SET NAMES utf8") );
       $conn->setAttribute( PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
    }
    catch(PDOException $e)
    {
        echo $sql . "<br>" . $e->getMessage();
    }
    
   
    $stmt = $conn->prepare( "INSERT INTO sahamiran (nemad,name,tedad,hajm,arzesh,diroz,avalin,akharinm,akharint,akharind,gimatm,gimatt,gimatd,kamtarin,bishtarin, eps ,pe,kharidt,kharidh,kharidg,froshg,froshh,frosht) VALUES (?, ?, ?, ?, ? ,?, ?, ?, ?, ? ,?, ?, ?, ?, ? ,?, ?, ?, ?, ?, ?, ?, ?)");
    $stmt->bindParam( 1, $nemad);
    $stmt->bindParam( 2, $name);
    $stmt->bindParam( 3, $tedad);
    $stmt->bindParam( 4, $hajm);
    $stmt->bindParam( 5, $arzesh);
    $stmt->bindParam( 6, $diroz);
    $stmt->bindParam( 7, $avalin);
    $stmt->bindParam( 8, $akharinm);
    $stmt->bindParam( 9, $akharint);
    $stmt->bindParam( 10, $akharind);    
    $stmt->bindParam( 11, $gimatm);
    $stmt->bindParam( 12, $gimatt);
    $stmt->bindParam( 13, $gimatd);
    $stmt->bindParam( 14, $kamtarin);
    $stmt->bindParam( 15, $bishtarin);    
    $stmt->bindParam( 16, $eps);
    $stmt->bindParam( 17, $pe);
    $stmt->bindParam( 18, $kharidt);
    $stmt->bindParam( 19, $kharidh);
    $stmt->bindParam( 20, $kharidg);    
    $stmt->bindParam( 21, $froshg);
    $stmt->bindParam( 22, $froshh);
    $stmt->bindParam( 23, $frosht);

   //echo $xlsx->rows();
   

    foreach ($xlsx->rows() as $fields)
    {
        $nemad = $fields[0];
        $name = $fields[1];
        $tedad = $fields[2];
        $hajm = $fields[3];
        $arzesh = $fields[4];
        $diroz = $fields[5];
        $avalin = $fields[6];
        $akharinm = $fields[7];
        $akharint= $fields[8];
        $akharind = $fields[9];
        $gimatm = $fields[10];
        $gimatt = $fields[11];
        $gimatd = $fields[12];
        $kamtarin = $fields[13];
        $bishtarin = $fields[14];
        $eps = $fields[15];
        $pe = $fields[16];
        $kharidt = $fields[17];
        $kharidh = $fields[18];
        $kharidg = $fields[19];
        $froshg = $fields[20];
        $froshh = $fields[21];
        $frosht = $fields[22];

        $stmt->execute();
        
    }
    }else {
		echo SimpleXLSX::parseError();
	}

**Comment by shuchkin** [comment]
check path 'xlsx/this.is.correct.xlsx'

**Comment by mansour161** [comment]
i found  this problem as you see the picture i was attach i was show this problem

 if sheet name is persian it didnt work

how can i solve this problem?
thanks

**Comment by shuchkin** [comment]
pls enable debug
https://github.com/shuchkin/simplexlsx#debug
I need detailed report

**Comment by mansour161** [comment]
hi 
debug give to me 
XML-entry not found | bad ZIP archive   
number 4 in table

**Comment by shuchkin** [comment]
try other xlsx reader, I think u have bad configired environment, so I can't repeat your error on my test machines

**Comment by mansour161** [comment]
thanks
