### ISSUE TITLE
Custom Number Format  ###0 getting outputed as yyyy-mm-dd 00:00:00

### ISSUE THREAD

**Issue by davidtoolin** [shuchkin/simplexlsx#63]
Sergey,   great tool.
Have this strange issue with it on a XLSX file that I am getting from a 3rd party by email, nightly.
I have written PHP wrapper around your tool, that gets the email from an IMAP account, then downloads the attachment and uses your tool to extract the data.
Two of the fields use a Custom Number Format ###0, and the output for these fields is in a Date/time format.
 `[GHIN Number] => 8231-10-07 00:00:00`
           ` [Local Number] => 1900-01-11 00:00:00`
            `[Prefix] =>` 
            `[First Name] => David`

The number should be:
```
 [0] => SimpleXMLElement Object
                                        (
                                            [@attributes] => Array
                                                (
                                                    [r] => A19
                                                    [s] => 9
                                                )

                                            [v] => 2312631.0
                                        )
```
Unfortunately I don't have any access to the formatting at the source.
I have attached the file but are worried it won't be very useful, since when I save it on my PC and send it to myself and run the PHP it works just fine. 
So I started digging around a bit.
I found some of you debug echo and turned them on.  Found this
   
```
  [numFmt] => Array
                (
                    [0] => SimpleXMLElement Object
                        (
                            [@attributes] => Array
                                (
                                    [numFmtId] => 50
                                    [formatCode] => ####0
                                )

                        )
```
And of course numFmtId =50 looks like it is a date time format.  Fortunately this gave me a work around for now.  Just edited the id 50 to '0';

If you can't duplicate this on your end would be happy to help more, just push me in the right direction.

[Roster Report.xlsx](https://github.com/shuchkin/simplexlsx/files/4082930/Roster.Report.xlsx)

**Comment by shuchkin** [comment]
try devel version

**Comment by davidtoolin** [comment]
Worked great, thanks.
One other little thing that is probably an enhancement request. The last column **Handicap Index** comes thru with some thing (Line Feed?, or CR?) Which makes it hard to match on.   Have to add strpos check and change the index.    
Not sure of the excel mechanism to get that field to have two rows different that some of the other two row fields. No Biggie.
Maybe replacing the hidden LF with a space makes sense, or a clean hidden tags option??
Or maybe the org generating this xlsx file is doing something wrong,
