### ISSUE TITLE
Sheet number in rows() does not work

### ISSUE THREAD

**Issue by e-v-medvedev** [shuchkin/simplexlsx#64]
Function returns all data in all sheets as if worksheetIndex not defined.

**Comment by shuchkin** [comment]
send me excel file to sergey.shuchkin@gmail.com

**Comment by e-v-medvedev** [comment]
Excuse me. This is actually my mistake. When displaying data by your module, I proceeded from the fact that the data in the file is correct. And when I saw the content that was erroneous in meaning, I thought that it came from the second page. Everything works fine for you. Thanks for the code. Sorry for the worries again.
