### ISSUE TITLE
Error reading xlsx file created with LibreOffice

### ISSUE THREAD

**Issue by e-v-medvedev** [shuchkin/simplexlsx#65]
Try this file with your module. In my case it do not extract data and skip_empty_rows option not work. This file was created with Excell, but later was modified with LibreOffice. Problems appeared after modification. Source file was read correctly.
[ФЕДЕРАЛЬНЫЕ ЕДИНИЧНЫЕ РАСЦЕНКИ НА КАПИТАЛЬНЫЙ РЕМОНТ ОБОРУДОВАНИЯ. Работы.xlsx](https://github.com/shuchkin/simplexlsx/files/4096794/default.xlsx)

**Comment by shuchkin** [comment]
пробуй 0.8.12

**Comment by e-v-medvedev** [comment]
Спасибо. Работает. Процедура установки composer (ом) ставит 0.8.11. Отсюда и проблема.

**Comment by shuchkin** [comment]
это я после этого баг репорта дописал несколько строк сегодня и залил 0.8.12
