### ISSUE TITLE
PHP version incompatibility?

### ISSUE THREAD

**Issue by ehwest** [shuchkin/simplexlsx#66]
I'm getting these error messages under error_reporting(E_ALL)

PHP Version 5.4.25

Strict Standards: Non-static method SimpleXLSX::parseData() should not be called statically in /opt/lampp/htdocs/ienterprise/urecipe.htm on line 36

$xlsx = SimpleXLSX::parseData( $filecontent, true, true).....{}

Fatal error: Using $this when not in object context in /opt/lampp/htdocs/ienterprise/simplexlsx.php on line 256

Loooks like this is easily fixed:
Just change the way the parse is called to the following:
   $xlsx = new  SimpleXLSX;
   $xlsx -> parseData( $filecontent, true );

**Comment by shuchkin** [comment]
pls update to 0.8.13
