### ISSUE TITLE
Warning Messages

### ISSUE THREAD

**Issue by Binapick** [shuchkin/simplexlsx#7]
I have another issue with the import of an Excel 2016 Sheet. I get following warning:

Warning:  gmdate() expects parameter 2 to be integer, float given in C:\xampp\htdocs\vhosts\tcup\lib\simplexlsx.class.php on line 418
I use the following code to import it:
````
$_xlsx = new SimpleXLSX("finswimming_Cup.xlsx");
if ($_xlsx->success()){
	$_noSheets = $_xlsx->sheetsCount();
	list($cols, $rows) = $_xlsx->dimension(10);

		print"<pre>";print_r( $_xlsx->rows(10) );print "</pre>";
}
````

**Comment by shuchkin** [comment]
pls update class https://github.com/shuchkin/simplexlsx/blob/master/simplexlsx.class.php
and try again
