### ISSUE TITLE
Auto parse percent value in cell 

### ISSUE THREAD

**Issue by dosangminh** [shuchkin/simplexlsx#74]
Hi author,

First, your lib help me a lot, thanks so much! 

I have a case which value in cell is percent, let say 10%, when parse it return me 0.1 which I can not use to show 10% , I can fix this by format the cell to text, but this option is not very good to end user. 

Looking forward to hear from you soon.

Regards,
Simon

**Comment by shuchkin** [comment]
simon, u kidding me )

```
foreach( $xlsx->rows() as $r ) {
  echo round( $r[0] * 100 ).'%'; // 10%
}
```

**Comment by dosangminh** [comment]
What if there are two cell which two different format : 10% and 0.1 , how to keep it exactly what it is really are.

**Comment by KevinBLT** [comment]
If you don't know the table you could use rowsEx and read format:
![image](https://user-images.githubusercontent.com/12692409/88544577-e7352100-d019-11ea-9425-7fd29b3f9dce.png)

It will say if the user set it to % value.
Nonetheless I would agree it could be handy to add "displayValue" to the array for user that just want to show the table as it was created. Everything else is for work with the data - which should be the default use case, I think.
