### ISSUE TITLE
XLSX saved on Office for Mac cannot be parsed

### ISSUE THREAD

**Issue by JmzTaylor** [shuchkin/simplexlsx#75]
Even after opening, editing and saving on a Windows computer the file still fails to be parsed.  SimpleXLSX does not error out.  Just returns empty data.
[error.xlsx](https://github.com/shuchkin/simplexlsx/files/4388377/error.xlsx)

**Comment by dele** [comment]
I have simillar problem, when i try to parse XLSX file from MAC i get this error "Unknown archive format" and wont parse table. Any ideas?

**Comment by shuchkin** [comment]
try 0.8.14

**Comment by JmzTaylor** [comment]
Thanks!
