### ISSUE TITLE
get active sheet

### ISSUE THREAD

**Issue by dosangminh** [shuchkin/simplexlsx#78]
Dear Sergey Shuchkin,

I have a case, if I upload 1 excel with 3 sheets, and I active sheet (3), it will alway read sheet (1) 

Is there any feature to set to alway read a active sheet? 

Thanks,
Simon

**Comment by shuchkin** [comment]
workbook = sheets, charts, pivottables...
so we can't detect active sheet
we can extract active tab 
```php
// unreliable method
$active_tab  = $xlsx->getEntryXML('xl/workbook.xml')->bookViews->workbookView[0]['activeTab'];
print_r( $xlsx->rows( $active_tab ) );
```

**Comment by shuchkin** [comment]
in 0.9.31 added shortcut $xlsx->activeSheet
```php
echo $xlsx->sheetName( $xlsx->activeSheet );
```
```
Sheet 2
```
