### ISSUE TITLE
XML-entry not found /xl/workbook.xml

### ISSUE THREAD

**Issue by GertCorstjens** [shuchkin/simplexlsx#79]
Hi,

I receive error "XML-entry not found /xl/workbook.xml" on parsing...

On version v0.8.3 it still worked... Attached the file.
Could you please let know if I'm doing something wrong?

[T_T_infoVVG2007945.xlsx](https://github.com/shuchkin/simplexlsx/files/4771152/T_T_infoVVG2007945.xlsx)

**Comment by shuchkin** [comment]
abs pathes fixed in 0.8.16
