### ISSUE TITLE
Minimum PHP Version?

### ISSUE THREAD

**Issue by 20Fourteen** [shuchkin/simplexlsx#8]
Is there a minimum PHP version? I can't seem to get it working, even using the examples.

**Comment by shuchkin** [comment]
try
<?php
ini_set('display_errors', true); 
ini_set('error_reporting', E_ALL);

**Comment by shuchkin** [comment]
ini_set('display_errors', true);
ini_set('error_reporting', E_ALL);

**Comment by 20Fourteen** [comment]
I must have done something wrong, all works now. Thank you for the fast reply and again for the wonderful library!
