### ISSUE TITLE
Unable to read some Excel files

### ISSUE THREAD

**Issue by vce-wabbott** [shuchkin/simplexlsx#80]
I'm running into an error "XML-entry not found /xl/workbook.xml" using SimpleXLSX v0.8.8 or v0.8.15 on some files that can be opened in Excel. Enclosed examples that generate the issue.

[amelia-vmc05.nj1.ipsoft.com 2019-07-24.xlsx](https://github.com/shuchkin/simplexlsx/files/4772806/amelia-vmc05.nj1.ipsoft.com.2019-07-24.xlsx)

[PRUDENTIAL_RVT_4.0.4.0_VCENTER1-MN315_5-29-20.xlsx](https://github.com/shuchkin/simplexlsx/files/4772793/PRUDENTIAL_RVT_4.0.4.0_VCENTER1-MN315_5-29-20.xlsx)

**Comment by shuchkin** [comment]
abs pathes fixed in 0.8.16

**Comment by vce-wabbott** [comment]
Verified things are working on a number of files that had the issue. Thanks much! FYI - version number was not bumped up to 0.8.16 in the source code.

**Comment by shuchkin** [comment]
0.8.17
