### ISSUE TITLE
Reading XLSX file from Google Drive

### ISSUE THREAD

**Issue by HaLeiVi** [shuchkin/simplexlsx#81]
Although the file, when downloaded using Google's https://drive.google.com/uc?export=download&id=xxxxxxx link downloads just fine when entered into the addressbar, if I pass that into SimpleXLSX I get the error, "Unknown archive format". It used to work. I wonder if Google is zipping it in some format unknown to the method being used in SimpleXLSX to test validity.

**Comment by shuchkin** [comment]
just u logged in, but SimpleXLSX no
try your link in chrome incognito

**Comment by HaLeiVi** [comment]
It's a generated link that directly picks up the file.

**Comment by shuchkin** [comment]
try download via any other http lbrary and use SimpleXLSX::parseData after
