### ISSUE TITLE
Cell data with a hyperlink

### ISSUE THREAD

**Issue by arkid** [shuchkin/simplexlsx#82]
Thanks for the library, it's great.  It almost does what I need.  Following your simple example of an XLS output as an html table almost works for me.  The only issue I have is that in the data I need to import, one of the columns has text values that are always defined with a hyperlink over them.   That seems to get lost in the process, how can I obtain that ?

**Comment by shuchkin** [comment]
try $xlsx->rowsEx()

**Comment by arkid** [comment]
Ok thanks, I'd seen that and wondered if there were other ways but yes now got it working.  For anyone else this is useful for:

`foreach( $xlsx->rowsEx() as $r ) {
						echo '<tr>';
						foreach ($r as $item){
							echo '<td>';
							if ($item["href"]){
								echo '<a href="'.$item["href"].'">'.$item["value"].'</a>';
							}else{
								echo $item["value"];
							}
							echo '</td>';
						}
						echo '</tr>';
					}
					echo '</table>';`
