### ISSUE TITLE
Sometimes unable to read urls from cells

### ISSUE THREAD

**Issue by arkid** [shuchkin/simplexlsx#83]
I've discovered that sometimes for a reason I can't completely clarify that the libraries code can not read hyperlinks defined on text in cells  

I've now massively simplified the problem xls that was shared with me to just a couple of rows in a single column yet still your library doesn't seem to be able to read the href.

I've searched the entire $xlsx object returned from

`$xlsx = SimpleXLSX::parse($savedPathFull)`

and it has no reference to the test.com domain that is in the hyperlink of one of the cells.    You could recreate this yourself with the attached sample xlsx and the command above.

[test.xlsx](https://github.com/shuchkin/simplexlsx/files/4912005/test.xlsx)

Any help really appreciated troubleshooting this.

**Comment by arkid** [comment]
Hi is there any chance of any guidance on this, I'd love to get this working and also make your library more robust in the process if possible.

**Comment by shuchkin** [comment]
in progress, there separate meta file for indexed URLS...

**Comment by arkid** [comment]
@shuchkin OK thank you so much! Looking forward to a new release :smiley:

**Comment by shuchkin** [comment]
try 0.8.18
thx for issue report
my first method was wrong

**Comment by arkid** [comment]
Amazing @shuchkin thanks so much, really appreciate it!
