### ISSUE TITLE
Date issue : date before 1900

### ISSUE THREAD

**Issue by fehrenmann** [shuchkin/simplexlsx#84]
Hello,

I encounter a problem parsing my excel file containing date before 1900 (for example 01/01/1885). 
Version simplexlsx : 0.8.11
PHP : 7.2

Is there a way to treat this kind of dates ? Thanks for your help

Please find below the error reported.

`ErrorException  : A non well formed numeric value encountered

  at /var/www/html/gide-insylva/vendor/shuchkin/simplexlsx/src/SimpleXLSX.php:940
    936| 
    937| 	public function unixstamp( $excelDateTime ) {
    938| 
    939| 		$d = floor( $excelDateTime ); // days since 1900 or 1904
  > 940| 		$t = $excelDateTime - $d;
    941| 
    942| 		if ( $this->date1904 ) {
    943| 			$d += 1462;
    944| 		}

  Exception trace:

  1   Illuminate\Foundation\Bootstrap\HandleExceptions::handleError("A non well formed numeric value encountered", "/var/www/html/gide-insylva/vendor/shuchkin/simplexlsx/src/SimpleXLSX.php", **["1885-01-01"])**
      /var/www/html/gide-insylva/vendor/shuchkin/simplexlsx/src/SimpleXLSX.php:940

  2   SimpleXLSX::unixstamp("1885-01-01")
`

**Comment by shuchkin** [comment]
My Excel save it as string
```
 [2] => Array
        (
            [0] => Array
                (
                    [type] => s
                    [name] => A3
                    [value] => 18.01.1825
                    [href] => 
                    [f] => 
                    [format] => mm-dd-yy
                    [r] => 3
                )
```

Send me your file sergey.shuchkin@gmail.com

**Comment by shuchkin** [comment]
There hybrid values (strings and dates), try change datetime format for unification

https://github.com/shuchkin/simplexlsx#datetime-helpers

```php
$xlsx = SimpleXLSX::parse( 'dates.xlsx');
$xlsx->setDateTimeFormat('Y-m-d');
print_r( $xlsx->rows() );
```

**Comment by fehrenmann** [comment]
Thanks a lot for your help Sergey, it works ! It was an issue due to hybrid values and bad setDateTimeFormat !
Kind regards from France ;-)

**Comment by shuchkin** [comment]
Je vous en prie )
