### ISSUE TITLE
Wrong dealing with libxml_get_last_error and sharedStrings problem

### ISSUE THREAD

**Issue by DMGPage** [shuchkin/simplexlsx#88]
I noticed, that some xlsx files saved with Microsoft Excel generates error. When tried to find, where is the problem I found that "/xl/sharedStrings.xml" sometimes contains:
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<sst xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"/>
```

Which is not parsed by "simplexml_load_string". And here are two problems: 1. I can't parse that file with your lib. 2. your lib genereates wrong error, because from the php documentation "libxml_get_last_error" can return "false". And in second problem "$e->message" and "$e->line" generates another error, because $e is "false".

**Comment by shuchkin** [comment]
try 0.8.19

**Comment by DMGPage** [comment]
Yes, now it works much better. Thanks!
