### ISSUE TITLE
Memory Limit Issue

### ISSUE THREAD

**Issue by Salman937** [shuchkin/simplexlsx#89]
I am trying to upload the heavy file now it's giving me this error

Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 86933080 bytes) in /Applications/XAMPP/xamppfiles/htdocs/Akash-projects/J/vendor/shuchkin/simplexlsx/src/SimpleXLSX.php on line 538

**Comment by shuchkin** [comment]
https://www.google.com/search?q=Fatal+error%3A+Allowed+memory+size
