### ISSUE TITLE
Sheet not found

### ISSUE THREAD

**Issue by sjnilan** [shuchkin/simplexlsx#9]
Even I set the sheet number some of xlsx files that have more than 25000 records give this error. 

```
public function worksheet( $worksheet_id ) {

		if ( isset( $this->sheets[ $worksheet_id ] ) ) {
			$ws = $this->sheets[ $worksheet_id ];
			
			if (isset($ws->hyperlinks)) {
				$this->hyperlinks = array();
				foreach( $ws->hyperlinks->hyperlink as $hyperlink ) {
					$this->hyperlinks[ (string) $hyperlink['ref'] ] = (string) $hyperlink['display'];
				}
			}
			
			return $ws;
		} else {
			**$this->error( 'Worksheet '.$worksheet_id.' not found.');**
			return false;
		}
	}
```

**Comment by shuchkin** [comment]
check this file by print_r( $xlxs->sheetNames() )
usually sheet IDs 1, 2, 3, 4, 5
but sometime 1, 2, 4, 5, 6

**Comment by sjnilan** [comment]
It shows empty :(
Array ( )
This file has 30590 rows. Shall I send this file to you?

**Comment by shuchkin** [comment]
go, sergey.shuchkin@gmail.com

**Comment by shuchkin** [comment]
try 0.7.3

**Comment by sjnilan** [comment]
new version doesn't read even small files.

**Comment by shuchkin** [comment]
pls download fixed version

**Comment by sjnilan** [comment]
In Local host it work fine. But remote server it isn't working. don't know why :(

**Comment by shuchkin** [comment]
try
ini_set('display_errors', true);
ini_set('error_reporting', E_ALL);
