### ISSUE TITLE
Uncaught Error: Call to undefined function simplexml_load_string()

### ISSUE THREAD

**Issue by Alejandrom8** [shuchkin/simplexlsx#90]
I just have ran the SimpleXLS.php file and get this error:

`
PHP Fatal error:  Uncaught Error: Call to undefined function simplexml_load_string() in /home/alex/Escritorio/Job/davines-table/vendor/SimpleXLSX.php:554
Stack trace:
#0 /home/alex/Escritorio/Job/davines-table/vendor/SimpleXLSX.php(428): SimpleXLSX->getEntryXML()
#1 /home/alex/Escritorio/Job/davines-table/vendor/SimpleXLSX.php(210): SimpleXLSX->_parse()
#2 /home/alex/Escritorio/Job/davines-table/index.php(5): SimpleXLSX::parse()
#3 {main}
  thrown in /home/alex/Escritorio/Job/davines-table/vendor/SimpleXLSX.php on line 554
`

My Info:

- PHP version: 7.4.3
- OS: Linux Ubuntu 20.04

How have happened:

I have run the php example that you have put in your github README.md file

```
require_once('./vendor/SimpleXLSX.php');

if ( $xlsx = SimpleXLSX::parse('./data/DirectorioExterno.xlsx') ) {
        print_r( $xlsx->rows() );
} else {
        echo SimpleXLSX::parse_error();
}
```

**Comment by shuchkin** [comment]
https://stackoverflow.com/questions/38793676/php-xml-extension-not-installed
