### ISSUE TITLE
extended versions using parse() get original object instead of extended

### ISSUE THREAD

**Issue by risner** [shuchkin/simplexlsx#92]
The patch provided fixes this issue for php 5.3+, but this link talks about a way to fix it in php 5.2 and below.

[https://stackoverflow.com/questions/5196476/php-5-2-equivalent-to-late-static-binding-new-static](url)

`--- simplexlsx-master/src/SimpleXLSX.php.orig	2020-10-04 15:05:05.000000000 -0400
+++ simplexlsx-master/src/SimpleXLSX.php	2020-10-04 15:05:27.000000000 -0400
@@ -204,7 +204,7 @@
 	}

 	public static function parse( $filename, $is_data = false, $debug = false ) {
-		$xlsx        = new self();
+		$xlsx        = new static();
 		$xlsx->debug = $debug;
 		if ( $xlsx->_unzip( $filename, $is_data ) ) {
 			$xlsx->_parse();`

**Comment by risner** [comment]
Apologizes, code doesn't seem to work with patches. Change "new self()" to "new static()" to allow others to extend the package and use parse() with the extended object instead of the original object.

**Comment by shuchkin** [comment]
we have a lot of 5.2 installs (I'll change self to static in 0.9 for PHP7)

just copy/paste ::parse method to your class now and change "new self" to "new static"

```php
class MyXLSX extends SimpleXLSX {

	public static function parse( $filename, $is_data = false, $debug = false ) {
		$xlsx        = new static();
		$xlsx->debug = $debug;
		if ( $xlsx->_unzip( $filename, $is_data ) ) {
			$xlsx->_parse();
		}
		if ( $xlsx->success() ) {
			return $xlsx;
		}
		self::parseError( $xlsx->error() );
		self::parseErrno( $xlsx->errno() );

		return false;
	}
}
```

**Comment by risner** [comment]
Thanks for the fast response.
I’ll await the 0.9 release.
I’m currently copying parse, but it’s a little more annoying than 
just copying it over. Both _unzip and _parse were private, and as such 
may not be called in a copy of parse().

It’s possible I made this more difficult, and there is a better way to 
define the ::parse() function. If that is true, please let me know. But 
copying it over verbatim didn’t work as _unzip and _parse could not be 
called.

Here is a functional parse() copy I’m using in production with the 
extended class:
     public static function parse( $f, $is_data = false, $debug = false 
) {

         $xlsx        = new static();
         $xlsx->debug = $debug;

         $reflector = new ReflectionObject($xlsx);
         $method = $reflector->getMethod('_unzip');
         $method->setAccessible(true);
         if ( $method->invoke( $xlsx, $f, $is_data ) ) {
             $reflector = new ReflectionObject($xlsx);
             $method = $reflector->getMethod('_parse');
             $method->setAccessible(true);
             $method->invoke( $xlsx );
         }
         if ( $xlsx->success() ) {
             return $xlsx;
         }
         self::parseError( $xlsx->error() );
         self::parseErrno( $xlsx->errno() );

         return false;
     }

**Comment by shuchkin** [comment]
see updated example

**Comment by shuchkin** [comment]
all private methods protected now

**Comment by risner** [comment]
Does this mean I don’t need to use the workaround with this version?
