### ISSUE TITLE
count(): Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by abuujurayj** [shuchkin/simplexlsx#95]
Above Error is thrown when am trying to get sheets count.

`$xlsx = SimpleXLSX_2020::parse($FileLocation);
echo $xlsx->sheetsCount();`

PHP version = 7.4.7

**Comment by shuchkin** [comment]
bad xml
xlsx generated with errors
send me file sergey.shuchkin@gmail.com
