### ISSUE TITLE
Deprecated function call on PHP 8

### ISSUE THREAD

**Issue by iKlsR** [shuchkin/simplexlsx#96]
>"Function libxml_disable_entity_loader() is deprecated"

Currently bypassing this with `error_reporting(E_ALL ^ E_DEPRECATED);` but first party support would be nice. :)        

https://php.watch/versions/8.0/libxml_disable_entity_loader-deprecation

https://github.com/phpmyadmin/phpmyadmin/commit/723c0095b9393588c93fd96aaa8d5c0c6fad1b17

**Comment by shuchkin** [comment]
fixed in 0.8.21

**Comment by iKlsR** [comment]
Thank you!
