### ISSUE TITLE
Парсер файла в консольном приложении

### ISSUE THREAD

**Issue by rozpuh** [shuchkin/simplexlsx#99]
Когда запускаю скрипт через браузер все работает. А когда через консоль, выдает ошибку XML-entry xl/worksheets/sheet1.xml parser error  line 593108

Проверял в консольном приложении, xlsx файл доступен для чтения.
Не могу понять в чем причина.
![Снимок экрана 2021-04-13 213239](https://user-images.githubusercontent.com/77786224/114602910-cbed6d00-9c9f-11eb-8139-9f3a8e26f20b.png)

**Comment by rozpuh** [comment]
Пробовал переименовать, пересохранить файл, не помогло. Даже файл которые пересохранил с другим именем через браузер читается, через консоль выдает ошибку. 

XML-entry xl/worksheets/sheet1.xml parser error  line 2

**Comment by rozpuh** [comment]
[3.xlsx](https://github.com/shuchkin/simplexlsx/files/6306058/3.xlsx)

Вот пример файла который я пересохранил с новым именем. Вот если запускать скрипт через браузер, то все работает, через консоль не хочет.

**Comment by shuchkin** [comment]
похоже ошибка окружения, включи отладку https://github.com/shuchkin/simplexlsx#debug

**Comment by rozpuh** [comment]
mmap() failed: [12] Cannot allocate memory

mmap() failed: [12] Cannot allocate memory

Fatal error: Out of memory (allocated 68423680) (tried to allocate 294912 bytes) in /home/jc406265/inside-auto.com/www/system/core/Exceptions.php on line 201

Fatal error: Uncaught Error: Class 'CI_Exceptions' not found in /home/jc406265/inside-auto.com/www/system/core/Common.php:196
Stack trace:
#0 /home/jc406265/inside-auto.com/www/system/core/Common.php(617): load_class('Exceptions', 'core')
#1 /home/jc406265/inside-auto.com/www/system/core/Common.php(689): _error_handler(1, 'Out of memory (...', '-', 201)
#2 [internal function]: _shutdown_handler()
#3 {main}
  thrown in /home/jc406265/inside-auto.com/www/system/core/Common.php on line 196
